In [3]:
# Import the raddom module
import random

In [4]:
random.randint(-90,90)

17

In [5]:
random.random()

0.9154611235009786

In [7]:
random_number = random.randint(-90, 89) + random. random()
random_number

-40.41474017435792

In [10]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1
latitudes

[79.56152586468868,
 -53.772920679472826,
 -42.60569047572139,
 -66.43077236735046,
 -42.335832191136454,
 -30.87988079932463,
 -70.66476997999472,
 45.38341969593073,
 81.16093986308218,
 70.46637710885385]

In [13]:
random.randrange(-90,90,step=1)

-7

In [14]:
random.randrange(-90,90,step=3)

15

In [15]:
random.uniform(-90,90)

-63.703367604855444

In [16]:
# Import the NumPy module.
import numpy as np

In [17]:
np.random.uniform(-90.000, 90.000)

-82.02554316285295

In [18]:
np.random.uniform(low=-90, high=90)

-18.30435432674166

In [19]:
np.random.uniform(-90.000, 90.000, size=50)

array([ 13.28307352, -74.84066617,  69.34884461, -47.12013271,
        23.28322127,  61.43535284, -83.53916665, -30.68941244,
        77.45098752,  45.03422101, -20.47048343, -18.071209  ,
        40.33431242,  44.84329991,  76.9547942 , -69.50136481,
       -29.91269602,  81.22876676, -69.70687651,  84.83772649,
       -65.60016213,  80.05505501,  20.20860313, -47.55180431,
        63.52837009, -60.10313395,  12.23610479,  -1.82514312,
        43.36549748, -51.4883923 ,  79.0935851 ,  51.21537109,
       -72.00225398,  78.71496589, -12.05568336,  76.82512031,
       -60.73748279, -86.40335415,  81.29771466, -87.52646265,
       -21.42219257, -22.42409787, -86.93118183, -21.13896332,
        58.13856944, -34.82097434,  66.25039776,  60.1620411 ,
       -64.17402731, -75.43088186])

In [20]:
# Import timeit.
import timeit

In [21]:
np.random.uniform(-90.000, 90.000, size=1500)

array([-14.29187539,  -6.8779992 , -23.15651626, ...,  -3.41606214,
        31.99016215,  84.34675868])

In [22]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

18.7 µs ± 1.04 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500. 
%timeit latitudes(1500)

2.32 ms ± 116 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 74.91213648, -62.68009683,   1.48930701, ..., -43.48385723,
         8.29255646, -29.59727893])

In [27]:
def latitudes_for_loop(size):
    latitudes = []
    for x in range(0,size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
    return latitudes
# Call the function with 1500. 
%timeit latitudes(1500)

2.17 ms ± 248 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
